version: '3.2'

services:

  proxy-service:
    image: nginx:1.16.0-alpine
    ports:
      - 3080:80
      - 3443:443
    volumes:
      - ./proxy-service/nginx.conf:/etc/nginx/nginx.conf
      # - ./proxy-service/server-sites-enabled:/etc/nginx/sites-enabled
      - ./proxy-service/location-sites-enabled:/etc/nginx/sites-enabled

  mock-json-service-404:
    build: ./mock-json-service
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - "FLASK_APP=app.py"
    volumes:
      - ./mock-json-service:/usr/src/app
    working_dir: /usr/src/app

  mock-json-service-posts:
    build: ./mock-json-service
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - "FLASK_APP=app.py"
      - "RESOURCE=posts"
    volumes:
      - ./mock-json-service:/usr/src/app
    working_dir: /usr/src/app

  mock-json-service-albums:
    build: ./mock-json-service
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - "FLASK_APP=app.py"
      - "RESOURCE=albums"
    volumes:
      - ./mock-json-service:/usr/src/app
    working_dir: /usr/src/app